# Used to generate conda environment to run engine and app

name: my_mip
channels:
  - conda-forge
dependencies:
  # Python version
  - python==3.9.13
  - pip==23.3.1

  # Baseline numerical manipulation
  - numpy==1.23.0
  - scipy==1.11.3

  # Statistical packages
  - scikit-learn==1.3.1

  # Notebooks
  - jupyter==1.0.0
  - jupyterlab==4.0.7

  # Hierarchical data packages
  - pandas==2.1.1

  # Plotting
  - matplotlib==3.8.0
  - plotly==5.17.0

  # Python Style and Formatting
  - autopep8==2.0.4
  - black==23.10.0
  - flake8==6.1.0
  - isort==5.12.0
  - pre-commit==3.5.0

  # Others
  - pathlib
  - setuptools==68.2.2
  - tqdm==4.66.1

  # testing
  - pytest


  # Packages not on conda list - require pip installation
  - pip:
    - -e . #install bottom up package from local file
